var searchData=
[
  ['database_0',['Database',['../class_app_1_1_database.html',1,'App']]],
  ['database_2ephp_1',['Database.php',['../_database_8php.html',1,'']]],
  ['datos_2',['La Base de Datos',['../sprint7_page.html#autotoc_md22',1,'']]],
  ['de_20bdd_20basada_20en_20tdd_3',['Documentacion de BDD basada en TDD',['../sprint6_page.html#autotoc_md15',1,'']]],
  ['de_20compra_4',['Comparación de Precios y Lista de Compra',['../index.html#autotoc_md6',1,'']]],
  ['de_20datos_5',['La Base de Datos',['../sprint7_page.html#autotoc_md22',1,'']]],
  ['de_20mink_6',['SPRINT 6. DOCUMENTACION BDD BASADA EN TDD E INTEGRACION DE MINK',['../sprint6_page.html',1,'']]],
  ['de_20mink_7',['de Mink',['../sprint6_page.html#autotoc_md18',1,'Configuracion de Mink'],['../sprint6_page.html#autotoc_md19',1,'Problemas en el uso de Mink']]],
  ['de_20mink_20y_20goutte_8',['Instalacion de Mink y Goutte',['../sprint6_page.html#autotoc_md17',1,'']]],
  ['de_20precios_20y_20lista_20de_20compra_9',['Comparación de Precios y Lista de Compra',['../index.html#autotoc_md6',1,'']]],
  ['de_20productos_20para_20almacenarlos_10',['Escaneo de Productos para Almacenarlos',['../index.html#autotoc_md4',1,'']]],
  ['de_20productos_20para_20desecharlos_11',['Escaneo de Productos para Desecharlos',['../index.html#autotoc_md5',1,'']]],
  ['decreasestock_12',['decreaseStock',['../class_app_1_1_controllers_1_1_product_controller.html#a86fd46670ddd4fa688d01e3e7fdd5f14',1,'App\Controllers\ProductController\decreaseStock()'],['../class_app_1_1_model_1_1_product.html#ae3cc0bf66a7ba3464c0dd318ee38a15f',1,'App\Model\Product\decreaseStock()']]],
  ['del_20bdd_3a_13',['Por lo que he buscado acerca del BDD:',['../sprint4_page.html#autotoc_md11',1,'']]],
  ['del_20proyecto_20a_20arduino_20esp_20web_14',['SPRINT 7. MIGRACION DEL PROYECTO A ARDUINO, ESP, WEB',['../sprint7_page.html',1,'']]],
  ['del_20proyecto_20stock_20manager_15',['Documentación del Proyecto STOCK MANAGER',['../md_docs_2_m_a_i_n_p_a_g_e.html',1,'']]],
  ['deleteproduct_16',['deleteProduct',['../class_app_1_1_controllers_1_1_product_controller.html#a1d4808feb859bbc80c8df01b2152ec95',1,'App\Controllers\ProductController\deleteProduct()'],['../class_app_1_1_model_1_1_product.html#aee688013d28a6ed193bee7eadc7c8da2',1,'App\Model\Product\deleteProduct()']]],
  ['desecharlos_17',['Escaneo de Productos para Desecharlos',['../index.html#autotoc_md5',1,'']]],
  ['documentación_20del_20proyecto_20stock_20manager_18',['Documentación del Proyecto STOCK MANAGER',['../md_docs_2_m_a_i_n_p_a_g_e.html',1,'']]],
  ['documentacion_20bdd_20basada_20en_20tdd_20e_20integracion_20de_20mink_19',['SPRINT 6. DOCUMENTACION BDD BASADA EN TDD E INTEGRACION DE MINK',['../sprint6_page.html',1,'']]],
  ['documentacion_20de_20bdd_20basada_20en_20tdd_20',['Documentacion de BDD basada en TDD',['../sprint6_page.html#autotoc_md15',1,'']]],
  ['doxygen_21',['Doxygen',['../sprint5_page.html#autotoc_md12',1,'']]],
  ['doxygen_20y_20bdd_20con_20behat_20instaurados_22',['SPRINT 5. DOXYGEN Y BDD CON BEHAT INSTAURADOS',['../sprint5_page.html',1,'']]],
  ['drivers_23',['Sobre Mink y sus drivers',['../sprint6_page.html#autotoc_md16',1,'']]]
];
